"""add unique constraint on news stock_id url

Revision ID: 80c5d41dfc18
Revises: ac70090494f9
Create Date: 2026-07-10 09:02:26.002491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c5d41dfc18'
down_revision: Union[str, None] = 'ac70090494f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_news_stock_url', 'news', ['stock_id', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_news_stock_url', 'news', type_='unique')
    # ### end Alembic commands ###
