"""add source column to news

Revision ID: b902a1652557
Revises: 80c5d41dfc18
Create Date: 2026-07-16 06:00:34.133524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b902a1652557'
down_revision: Union[str, None] = '80c5d41dfc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'source')
    # ### end Alembic commands ###
