"""add view_count to stocks

Revision ID: d84982e06d2f
Revises: b902a1652557
Create Date: 2026-07-16 08:51:00.715050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84982e06d2f'
down_revision: Union[str, None] = 'b902a1652557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'stocks',
        sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'view_count')
    # ### end Alembic commands ###
